### ISSUE TITLE
`collectingGeneratedAndRetrievedCallGraphs` 

### ISSUE THREAD

**Issue by amphioxis** [fasten-project/fasten-pypi-plugin#23]
Uncommenting this [line](https://github.com/fasten-project/fasten-pypi-plugin/blob/51b82599f3027a377785ec947e1fe40e582a8a6c/src/fasten/__main__.py#L50) results in:

undefined-variable: Undefined variable 'collectingGeneratedAndRetrievedCallGraphs'

If that one is working, do we still need the others, like [this](https://github.com/fasten-project/fasten-pypi-plugin/blob/51b82599f3027a377785ec947e1fe40e582a8a6c/src/fasten/__main__.py#L52) one and [this](https://github.com/fasten-project/fasten-pypi-plugin/blob/51b82599f3027a377785ec947e1fe40e582a8a6c/src/fasten/__main__.py#L53) one?

**Comment by amphioxis** [comment]
Ok, I changed that, but now I am facing `undefined-variable: Undefined variable 'all_pkgs'` error.
Also, the linter still tells me `unused-variable: Unused variable 'LCVurl'`.
Could you create a branch from [main](https://github.com/fasten-project/fasten-pypi-plugin/tree/main), where you fix that, create a pull request and assign that to me as a reviewer so I can have a look? That would be more clean than using Issues.
It would also be good if you could review that pull request [here](https://github.com/fasten-project/fasten-pypi-plugin/pull/22) and merge it.

Thx!

**Comment by michelescarlato** [comment]
@lisa-noeth , @amphioxis am I wrong, or do you want me to review a PR with only this modification:
https://github.com/fasten-project/fasten-pypi-plugin/pull/22/files

**Comment by michelescarlato** [comment]
I am simply not running pypi plugin with your same imports.
So I cannot be sure that my approach is then valid for your execution.

Here you can find the fix:

https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/src/fasten/__main__.py#L46-L47




The linter tells you that because LCVurl is the address of LCV (on lima), that is used for lcv assessments and to check if licenses are in spdx format.
Probably in the version of `main` you are looking at, those functions still are commented (or removed).

--> ref. - `unused-variable: Unused variable 'LCVurl'`.
https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/src/fasten/__main__.py#L35


Welcome.

**Comment by amphioxis** [comment]
Yes, I see that changes. But we should make sure that we have a running main. So could you please open a new branch from main. and also change those things there, open a Pull Request, asign it to me for review, and then I'll test it. This way, we can come closer to a running main step by step.

**Comment by amphioxis** [comment]
What command is your IDE using to run that code? I am using vim with a specific setup of plugins.

**Comment by michelescarlato** [comment]
`script path`

`/home/michelescarlato/gitrepo-pypi-plugin/fasten-pypi-plugin/src/fasten/__main__.py`


`Parameters`

`--product fasten-pypi-plugin \         --pkg_name fasten-pypi-plugin \         --project_path ./ \         --timestamp 42 \         --version 1.0 \         --requirements ../../requirements.txt \         --fasten_data callGraphs/ \         --scg_path callGraphs/
`

(you can see them in the Configuration tab on the right side of the screenshot)


![image](https://user-images.githubusercontent.com/10910590/174270775-298aabcf-3ab8-43cb-8b6d-c8718504d837.png)

**Comment by amphioxis** [comment]
Ok, that means your IDE is running `python3 __main__.py --arguments` like mentioned before. My "IDE" is doing the same, and I also can't run it with the `fasten.` package declaration (and always have to remove it in my working branches - don't know a better workaround). But, as mentioned earlier, the enduser won't run `python3 __main__.py` but `fasten --arguments` after installing this package, and for the installation process, the package declaration `fasten` is important.

**Comment by amphioxis** [comment]
> So I cannot open a PR without changing all the imports.

You can open a new branch from `main`, remove `fasten.` from the import, apply your changes, test them, and if you are satisfied, put `fasten.` back, open a Pull Request and so on.
After this, continue your work on another branch and wait for my review.

**Comment by michelescarlato** [comment]
> Here you can find the fix:
> 
> https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/src/fasten/__main__.py#L46-L47
> 
> The linter tells you that because LCVurl is the address of LCV (on lima), that is used for lcv assessments and to check if licenses are in spdx format. Probably in the version of `main` you are looking at, those functions still are commented (or removed).
> 
> --> ref. - `unused-variable: Unused variable 'LCVurl'`. https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/src/fasten/__main__.py#L35
> 
> Welcome.

I think from this main you will find the fix you need.
