### ISSUE TITLE
oscg.json missing.

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten-pypi-plugin#24]
Hi @amphioxis ,

I cannot see the oscg.json in the indicated directory.

Could you please have a look?

(I am running this [main.py](https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/src/fasten/__main__.py), feel free to switch branch and give it a try - I hope the import clauses will function to you)

![image](https://user-images.githubusercontent.com/10910590/174116312-1e28ac64-6b38-4e77-9bb7-af44a28cc97b.png)

**Comment by amphioxis** [comment]
Hey,
I had a small look, and it seems that the Call Graphs can't be generated. They all result in:
`No such file or directory /usr/bin/time`
and
`directoryName/callgraphs/i/importlib-metadata/4.11.4/cg.json has not been generated`

Are you sure that the Stitched Call Graph is generated?

**Comment by michelescarlato** [comment]
> Hey, I had a small look, and it seems that the Call Graphs can't be generated. They all result in: `No such file or directory /usr/bin/time` and `directoryName/callgraphs/i/importlib-metadata/4.11.4/cg.json has not been generated`
> 
> The Stitched Call Graph is empty and therefore, no Optimized Stitched Call Graph is generated. I agree that the output message is misleading.
> 

Yes, it is generated.
[Here](https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/src/fasten/callGraphs/pipup.json) is the one that is generated.
[pipup.json.txt](https://github.com/fasten-project/fasten-pypi-plugin/files/8926179/pipup.json.txt)

**Comment by amphioxis** [comment]
Ok, but it was not generated for me. So we should first find out why it is not generated for me.
I checked out `main-michele-15th-june` and ran:
```
python3 __main__.py \
        --product fasten-pypi-plugin \
        --pkg_name fasten-pypi-plugin \
        --project_path ./ \
        --timestamp 42 \
        --version 1.0 \
        --requirements ../../requirements.txt \
        --fasten_data callGraphs/ \
        --scg_path callGraphs/
```

**Comment by michelescarlato** [comment]
I am talking about `pipup` package.

`python3 __main__.py --product pipup --pkg_name pipup --project_path pipup/ --timestamp 42 --version 1.0 --requirements pipup/requirements.txt --fasten_data callGraphs/ --scg_path callGraphs/ --spdx_license MIT`

**Comment by amphioxis** [comment]
> script path
> 
> /home/michelescarlato/gitrepo-pypi-plugin/fasten-pypi-plugin/src/fasten/__main__.py
> 
> Parameters
> 
> 
> --product fasten-pypi-plugin \ --pkg_name fasten-pypi-plugin \ --project_path ./ \ --timestamp 42 \ --version 1.0 \ --requirements ../../requirements.txt \ --fasten_data callGraphs/ \ --scg_path callGraphs/
> 
> (you can see them in the Configuration tab on the right side of the screenshot)

Ok, that means your IDE is running python3 __main__.py --arguments like mentioned before. My "IDE" is doing the same, and I also can't run it with the fasten. package declaration (and always have to remove it in my working branches - don't know a better workaround). But, as mentioned earlier, the enduser won't run python3 __main__.py but fasten --arguments after installing this package, and for the installation process, the package declaration fasten is important.

**Comment by michelescarlato** [comment]
Ok.

So did you finally see the optimized call graph ?

**Comment by amphioxis** [comment]
No. I am currently working on enrichment and I don't think it makes sense to fix something on a far away branch while at the same time `main` is not working.
I can also fix `main` myself, but as I don't know your code, I'll reset `main` to the last working state (the one mentioned in the deliverable) and merge your changes step by step.
Let me know if you want me do it.

**Comment by michelescarlato** [comment]
Feel free to do what you think is better.

I was just asking if it was possible to see the optimized stitched call graph, after generating locally the call graphs for missing packages.

**Comment by amphioxis** [comment]
So you are not trying to fix `main`?

**Comment by amphioxis** [comment]
Yes, I tried that, and of course that small fix is working and I could push that myself. But after that, other things don't work, therefore, I asked you to open a new branch from main, fix it there, open a pull request, assign that to me for review, so I can update the other things not working there. Do you want me create Issues for each small step?
The whole dependency resolution is not working for me, the Call Graph generation you implemented also not. How many Issues am I supposed to open?
The only way `main` is currently working, is by commenting out all your changes, that can't be the solution.

**Comment by michelescarlato** [comment]
As shown in this picture:
https://github.com/fasten-project/fasten-pypi-plugin/issues/24#issue-1273786354

Dependency resolution is functioning.
Local call graph generation also.
Stitching also.

I don't know if there is a specific (to the package that I am analyzing, pipup) reason why the optimization is not generating an output.

If you checkout `main-michele-15th-june` branch, you can try to see why dependency resolution and local call graph generation are not functioning for you.

The main here run correctly:
https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/src/fasten/__main__.py

If something is generating an error, could be related to some missing dependency (tbh I am not sure if this [requirements.txt](https://github.com/fasten-project/fasten-pypi-plugin/blob/main-michele-15th-june/requirements.txt) is updated).

[I need to rest more my eyes, sorry if I cannot be more helpful]

**Comment by michelescarlato** [comment]
For example, to run it from shell:

```
mkdir gitrepo-test

cd gitrepo-test

git clone git@github.com:fasten-project/fasten-pypi-plugin.git

cd fasten-pypi-plugin

git checkout main-michele-15th-june

pip install -r requirements.txt 

cd src/fasten

python3 __main__.py --product pipup --pkg_name pipup --project_path pipup/ --timestamp 42 --version 1.0 --requirements pipup/requirements.txt --fasten_data callGraphs/ --scg_path callGraphs/ --spdx_license MIT

```

This should be running the whole thing.

The problem, apart from not seeing the optimized stitched call graph (OSCG), is that the local call graph generation does not always function correctly.

So, I don't know if it could be related to the OSCG process.
For sure, the stitched call graph is in the right place also if for some package the call graphs are not generated locally.

**Comment by amphioxis** [comment]
I merged your @michelescarlato changes in [cg_generation_fixes](https://github.com/fasten-project/fasten-pypi-plugin/tree/cg_generation_fixes) and now, the Optimized Stitched Call Graph is created. The problem was, that the module [executeCallGraphGenerator](https://github.com/fasten-project/fasten-pypi-plugin/blob/cg_generation_fixes/src/fasten/executeCallGraphGenerator.py) is not able to create a Call Graph for the locally created package. So that Call Graph was missing and therefore, the Optimized Stitched Call Graph was empty.
