### ISSUE TITLE
Please pick another package name, as "fasten" is already taken by the fasten-python-plugins package

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten-pypi-plugin#28]
https://github.com/fasten-project/fasten-pypi-plugin/blob/6a87fd01718402cd2ca0cd585d5cc84109e1193b/setup.cfg#L2

Already taken by:
https://github.com/fasten-project/fasten-python-plugins

This causes installation problems and name clashes.

**Comment by amphioxis** [comment]
Hey @MagielBruntink ,
ok, I'll change it to `fasten-pypi-plugin`.

The command to run the plugin will still be [`fasten`](https://github.com/fasten-project/fasten-pypi-plugin/blob/6a87fd01718402cd2ca0cd585d5cc84109e1193b/setup.cfg#L25), is that ok?

**Comment by amphioxis** [comment]
Done.
