### ISSUE TITLE
Generating Call Graph. And doubts. 

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten-pypi-plugin#3]
@vitsalis @StefanosChaliasos 
Dear Vitalis and Stefanos,

I am helping @amphioxis Martin to understand how to implement the fasten PyPI plugin (D2.7).
Following his reasonings, it comes a doubt regarding the call graphs creation when they are not present in the database. 

So, Martin integrates into the [`createCallGraph.py` the call creation using the function CallGraphGenerator imported from the pycg package](https://github.com/fasten-project/fasten-pypi-plugin/blob/development/src/fasten/createCallGraph.py#L3).

My question is, are we proceeding correctly?

My doubt is this one:
" If there are call graphs in the database, is there any fasten-plugin able to create it, or should it be implemented now?"

Thank you in advance for your time and consideration,
Michele

**Comment by vitsalis** [comment]
Hi Michele,

From a quick check it looks like you're correctly using the `CallGraphGenerator` class. In the case that a call graph is not present in the database, one should create it manually using the process that you're following in the script.

**Comment by michelescarlato** [comment]
Thank you, Vitalis. 
Sorry for the late reply.
I am trying to help out Martin day by day, but this last week has been a little busy.
I am sure @amphioxis Martin is going to open an issue to understand better the call graph format provide by the  
`/mvn/packages/{pkg}/{pkg_ver}/callgraph` endpoint.

Thank you for your constant help.
Sincerely,
Michele
