### ISSUE TITLE
pypi-plugin fails for analysis upon fabric package

### ISSUE THREAD

**Issue by amphioxis** [fasten-project/fasten-pypi-plugin#32]
Running the [fasten-pypi-plugin](https://github.com/fasten-project/fasten-pypi-plugin/tree/cg_generation_fixes) (inside `/src/fasten/`) on the [fabric](https://github.com/fabric/fabric) package via
```
python3 __main__.py \
    --product fabric \
    --pkg_name fabric \
    --project_path path/to/fabric/ \
    --timestamp 42 \
    --version 1.0 \
    --requirements path/to/fabric/dev-requirements.txt \
    --fasten_data ./fasten_data/ \
    --scg_path ./StitchedCallGraph/
 ```
 results in two problems:

1.  **`file not found` error:**
The problematic code is [here](https://github.com/fasten-project/fasten-pypi-plugin/blob/8329487634d7be9cc3f01fa95b6d2b1e66f49ad3/src/fasten/executePypiResolver.py#L9).
 Adding `print(package_list[1])` [here](https://github.com/fasten-project/fasten-pypi-plugin/blob/8329487634d7be9cc3f01fa95b6d2b1e66f49ad3/src/fasten/executePypiResolver.py#L13) prints `set()` (an empty set) and therefore, the loop [here](https://github.com/fasten-project/fasten-pypi-plugin/blob/8329487634d7be9cc3f01fa95b6d2b1e66f49ad3/src/fasten/executePypiResolver.py#L14) is not accessed and the file can't be created.
2. **Process stucks "endless":**
On the second run with the same command, the process stucks endless [here](https://github.com/fasten-project/fasten-pypi-plugin/blob/8329487634d7be9cc3f01fa95b6d2b1e66f49ad3/src/fasten/executePypiResolver.py#L9).
This can be "solved" by changing the [TMP_DIR](https://github.com/fasten-project/fasten-pypi-plugin/blob/8329487634d7be9cc3f01fa95b6d2b1e66f49ad3/src/fasten/pypiResolver.py#L31) to `./fasten_data`. This folder will be [deleted](https://github.com/fasten-project/fasten-pypi-plugin/blob/8329487634d7be9cc3f01fa95b6d2b1e66f49ad3/src/fasten/__main__.py#L38) before the plugin starts its analysis.
However, if I do that, the process didn't stuck endless anymore, but now, also for the [pipup](https://github.com/revsys/pipup) package, the set stays empty.
To try that, replace `fabric` with `pipup` and `dev-requirements.txt` with `requirements.txt` on the command above.
Whats also strange is, that somehow, a new `src/` and `pycg-data/` folder is created in `src/fasten/` by doing that.
I don't know where these folders suddenly comes from.

**Comment by gdrosos** [comment]
Could you please clarify the steps to reproduce the issue? I tried to reproduce it by checking out at either main branch or cg_generation_fixes and i recieved the errors:  `ModuleNotFoundError: No module named 'fasten.enrichOSCG' `and `ModuleNotFoundError: No module named  'fasten.executeCallGraphGenerator'`, respectively.

**Comment by gdrosos** [comment]
I tried using separately the pypi resolver for the same requirements txt file (`python3 entrypoint -r requirements.txt `) and I could retrieve the dependency set. Please note  that the transitive dependency set consists of 131 dependencies so the resolver needing an extensive amount of time to finish the process is an expected behaviour:
```json
{
    "input": "requirements.txt",
    "status": true,
    "packages": {
        "XStatic-bootswatch": {
            "package": "XStatic-bootswatch",
            "version": "3.3.7.0"
        },
        "Babel": {
            "package": "Babel",
            "version": "2.10.3"
        },
        "importlib-metadata": {
            "package": "importlib-metadata",
            "version": "4.8.3"
        },
       .....
        "osprofiler": {
            "package": "osprofiler",
            "version": "3.4.3"
        }
    }
}
```

**Comment by amphioxis** [comment]
Hey @gdrosos,
thx for your reply!

**for the first message:**
You could just remove `fasten.` in the import lines and it should work.
Another way would be to install the plugin like mentioned in the [readme.md](https://github.com/fasten-project/fasten-pypi-plugin) and run `fasten --arguments`.
Sry, I forgot to mention that I am talking about the [cg_generation_fixes](https://github.com/fasten-project/fasten-pypi-plugin/tree/cg_generation_fixes)-branch.

**for the second message:**
On which `requirements.txt` did you run this test?
I understand, that it could take a long time to receive the dependencies. But on the second try, it shouldn't take longer than on the first try. As far as I understand, everything is sequential, so there are no parallel processes. Therefore, the whole dependency set should be received before the program went on to write a new `requirements` file.
What is strange is, that for the `pipup` package everything works smoothly.

Nonetheless I'll check out if the `pypi-resolver` is wrongly integrated.

**Comment by amphioxis** [comment]
Hey @gdrosos,
I can confirm, that it works with the [dev-requirements.txt](https://github.com/fabric/fabric/blob/main/dev-requirements.txt) of the fabric package if I remove [line 1](https://github.com/fabric/fabric/blob/c6d7b7bfe71575fe8f927fa13701c7db81ffd82b/dev-requirements.txt#L1).
So the problem is the format of the `requirements.txt` file, which is not a big problem as that is provided by the developers. I updated the [README.md](https://github.com/fasten-project/fasten-pypi-plugin#fasten-pypi-plugin) to mention the format required for the plugin to work.
