### ISSUE TITLE
Receive Call Graphs from FASTEN

### ISSUE THREAD

**Issue by amphioxis** [fasten-project/fasten-pypi-plugin#4]
Hey @vitsalis
I tried to stitch the Call Graphs received from FASTEN (using your [pycg-stitch](https://github.com/fasten-project/pycg-stitch) tool), however, I get error messages and I guess they are caused by a different format of the received Call Graphs and the example [Call Graphs](https://github.com/fasten-project/pycg-stitch/tree/master/benchmark/micro/call-graphs).
I guess the [endpoints](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects) are implemented by @MihhailSokolov and currently I am still using the [docker deployment](https://github.com/fasten-project/fasten-docker-deployment) which says (if you scroll down) that the basic endpoints work for python. Indeed, I can receive information from there, but the question is, do we need special endpoints for python (like a different format) or am I using the wrong ones?

Thanks for your help!

**Comment by vitsalis** [comment]
Hello @amphioxis 

I believe that indeed the basic endpoints work for Python. Maybe Mihhail can verify.

It would help a lot if you could provide a sample output call graph and the errors that it generates. Thanks!

**Comment by amphioxis** [comment]
Yes of course, this is the Call Graph for the astroid:2.5.7 package created by the `callgraph` endpoint:

`[{"source_id": 77976, "target_id": 78350}, {"source_id": 77975, "target_id": 77976}, {"source_id": 77974, "target_id": 77976}, {"source_id": 77979, "target_id": 78471}, {"source_id": 77978, "target_id": 78020}, {"source_id": 77981, "target_id": 78696}, {"source_id": 77989, "target_id": 78696}, {"source_id": 77997, "target_id": 78696}, {"source_id": 78003, "target_id": 1317}, {"source_id": 78003, "target_id": 77980}]`

The error message says:

`Traceback (most recent call last):
  File "pypi-Plugin-venv/fasten-pypi-plugin/src/fasten/main.py", line 10, in <module>
    class Main:
  File "pypi-Plugin-venv/fasten-pypi-plugin/src/fasten/main.py", line 37, in Main
    StitchCallGraph().stitchCallGraph(pathsToCallGraphs.call_graph)
  File "pypi-Plugin-venv/fasten-pypi-plugin/src/fasten/stitchCallGraph.py", line 13, in stitchCallGraph
    stitcher = Stitcher(call_graphs)
  File "pypi-Plugin-venv/lib/python3.9/site-packages/pycg_stitch-0.0.1-py3.9.egg/stitcher/stitcher.py", line 44, in __init__
  File "pypi-Plugin-venv/lib/python3.9/site-packages/pycg_stitch-0.0.1-py3.9.egg/stitcher/stitcher.py", line 91, in _parse_cgs
TypeError: list indices must be integers or slices, not str
`

If I switch to the `metadata` endpoint I got as "Call Graph":

`{"package_name": "astroid", "version": "2.5.7", "metadata": {}}` 

and the error message says:

`Traceback (most recent call last):
  File "pypi-Plugin-venv/fasten-pypi-plugin/src/fasten/main.py", line 10, in <module>
    class Main:
  File "pypi-Plugin-venv/fasten-pypi-plugin/src/fasten/main.py", line 37, in Main
    StitchCallGraph().stitchCallGraph(pathsToCallGraphs.call_graph)
  File "pypi-Plugin-venv/fasten-pypi-plugin/src/fasten/stitchCallGraph.py", line 13, in stitchCallGraph
    stitcher = Stitcher(call_graphs)
  File "pypi-Plugin-venv/lib/python3.9/site-packages/pycg_stitch-0.0.1-py3.9.egg/stitcher/stitcher.py", line 44, in __init__
  File "pypi-Plugin-venv/lib/python3.9/site-packages/pycg_stitch-0.0.1-py3.9.egg/stitcher/stitcher.py", line 91, in _parse_cgs
KeyError: 'product'
`

**Comment by vitsalis** [comment]
I believe the error is due to the first call graph not following the [FASTEN format](https://github.com/fasten-project/fasten/wiki/Revision-Call-Graph-format#version-2-1). I am not very familiar with the API though.

Is this the expected behavior @ashkboos  @MihhailSokolov ?

**Comment by MihhailSokolov** [comment]
> I believe the error is due to the first call graph not following the [FASTEN format](https://github.com/fasten-project/fasten/wiki/Revision-Call-Graph-format#version-2-1). I am not very familiar with the API though.
> 
> Is this the expected behavior @ashkboos  @MihhailSokolov ?

I don't really know, sorry. I haven't worked with Python CGs. I only know that they have their own format which is described in the wiki.

**Comment by amphioxis** [comment]
I mean, `pycg` is creating the right format and it is running inside the [`fasten-pycg`](https://github.com/fasten-project/fasten-docker-deployment/blob/501d944c0f0895d50dcf3b0210831e5791b2320b/docker-compose.yml#L595) container.
So the question is:
If I [feed](https://github.com/fasten-project/fasten-docker-deployment#feeding-the-pipeline) the database with package information, this information is send to the [`kafka`](https://github.com/fasten-project/fasten-docker-deployment/blob/501d944c0f0895d50dcf3b0210831e5791b2320b/docker-compose.yml#L37) container. What happens with that information, does the `pycg` container use that information to create a Call Graph for those packages and why, how, and where does the Call Graph format changes?

Maybe @MagielBruntink knows?

**Comment by MagielBruntink** [comment]
Hi all,

I am recreating the Python/PyPi pipeline and running into issues with the Python callgraphs. It seems the MetadataDB plugin assumes the new callsite format used by JavaCgOpal, which is not currently produced by PyCG. This leads to NPE's in the MetadataDB plugin, see one of the logs below.

The problematic code is here: https://github.com/fasten-project/fasten/blob/142891de4147f9bb50503b3a3b08727d9be96cfa/core/src/main/java/eu/fasten/core/data/graphdb/ExtendedGidGraph.java#L82

I think that currently only works for Java, and fixes should be implemented for Python and C. @ashkboos @MihhailSokolov Please provide your thoughts on what should happen there.

```
{
   "input": {
      "input": {
         "requires_dist": [],
         "product": "namesss",
         "version_timestamp": 1581173493,
         "version": "0.1.0"
      },
      "plugin_version": "0.0.1",
      "payload": {
         "product": "namesss",
         "metadata": {
            "loc": 21,
            "max_rss": 20048,
            "time_elapsed": 0.07,
            "num_files": 3
         },
         "nodes": 9,
         "forge": "PyPI",
         "generator": "PyCG",
         "depset": [],
         "version": "0.1.0",
         "modules": {
            "internal": {
               "/gen_names_bozydar/": {
                  "sourceFile": "gen_names_bozydar/__init__.py",
                  "namespaces": {
                     "2": {
                        "metadata": {
                           "last": 0,
                           "first": 0
                        },
                        "namespace": "/gen_names_bozydar/"
                     }
                  }
               },
               "/gen_names_bozydar.gen_names_bozydar/": {
                  "sourceFile": "gen_names_bozydar/gen_names_bozydar.py",
                  "namespaces": {
                     "1": {
                        "metadata": {
                           "last": 11,
                           "first": 1
                        },
                        "namespace": "/gen_names_bozydar.gen_names_bozydar/"
                     }
                  }
               },
               "/setup/": {
                  "sourceFile": "setup.py",
                  "namespaces": {
                     "0": {
                        "metadata": {
                           "last": 18,
                           "first": 1
                        },
                        "namespace": "/setup/"
                     }
                  }
               }
            },
            "external": {
               "names": {
                  "sourceFile": "",
                  "namespaces": {
                     "6": {
                        "metadata": {},
                        "namespace": "//names//names.get_full_name"
                     }
                  }
               },
               "setuptools": {
                  "sourceFile": "",
                  "namespaces": {
                     "3": {
                        "metadata": {},
                        "namespace": "//setuptools//setuptools.setup"
                     },
                     "4": {
                        "metadata": {},
                        "namespace": "//setuptools//setuptools.find_packages"
                     }
                  }
               },
               "argparse": {
                  "sourceFile": "",
                  "namespaces": {
                     "7": {
                        "metadata": {},
                        "namespace": "//argparse//argparse.ArgumentParser"
                     }
                  }
               },
               ".builtin": {
                  "sourceFile": "",
                  "namespaces": {
                     "5": {
                        "metadata": {},
                        "namespace": "//.builtin//len"
                     },
                     "8": {
                        "metadata": {},
                        "namespace": "//.builtin//print"
                     }
                  }
               }
            }
         },
         "graph": {
            "internalCalls": [],
            "externalCalls": [
               [
                  "0",
                  "3",
                  {}
               ],
               [
                  "0",
                  "4",
                  {}
               ],
               [
                  "1",
                  "5",
                  {}
               ],
               [
                  "1",
                  "6",
                  {}
               ],
               [
                  "1",
                  "7",
                  {}
               ],
               [
                  "1",
                  "8",
                  {}
               ]
            ],
            "resolvedCalls": []
         },
         "sourcePath": "/mnt/fasten/sources/n/namesss/0.1.0",
         "timestamp": "1581173493"
      },
      "created_at": 1626167775,
      "plugin_name": "PyCG"
   },
   "plugin_version": "0.1.2",
   "err": {
      "stacktrace": [
         "java.base/java.util.Objects.requireNonNull(Unknown Source)",
         "java.base/java.util.Arrays$ArrayList.<init>(Unknown Source)",
         "java.base/java.util.Arrays.asList(Unknown Source)",
         "eu.fasten.core.data.graphdb.ExtendedGidGraph.lambda$toJSON$2(ExtendedGidGraph.java:82)",
         "java.base/java.util.HashMap.forEach(Unknown Source)",
         "eu.fasten.core.data.graphdb.ExtendedGidGraph.toJSON(ExtendedGidGraph.java:78)",
         "eu.fasten.analyzer.metadataplugin.MetadataDBExtension.produce(MetadataDBExtension.java:188)",
         "eu.fasten.server.plugins.kafka.FastenKafkaPlugin.handleProducing(FastenKafkaPlugin.java:275)",
         "eu.fasten.server.plugins.kafka.FastenKafkaPlugin.processRecord(FastenKafkaPlugin.java:261)",
         "eu.fasten.server.plugins.kafka.FastenKafkaPlugin.handleConsuming(FastenKafkaPlugin.java:186)",
         "eu.fasten.server.plugins.kafka.FastenKafkaPlugin.run(FastenKafkaPlugin.java:145)",
         "eu.fasten.server.plugins.kafka.FastenKafkaPlugin.start(FastenKafkaPlugin.java:163)",
         "java.base/java.util.ArrayList.forEach(Unknown Source)",
         "eu.fasten.server.FastenServer.run(FastenServer.java:206)",
         "picocli.CommandLine.executeUserObject(CommandLine.java:1919)",
         "picocli.CommandLine.access$1100(CommandLine.java:145)",
         "picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)",
         "picocli.CommandLine$RunLast.handle(CommandLine.java:2326)",
         "picocli.CommandLine$RunLast.handle(CommandLine.java:2291)",
         "picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)",
         "picocli.CommandLine.execute(CommandLine.java:2058)",
         "eu.fasten.server.FastenServer.main(FastenServer.java:352)"
      ],
      "error": "NullPointerException"
   },
   "consumed_at": 1626167775,
   "host": "ec934779f2ae",
   "created_at": 1626167776,
   "plugin_name": "MetadataDBPythonExtension"
}
```

**Comment by MagielBruntink** [comment]
> I mean, `pycg` is creating the right format and it is running inside the [`fasten-pycg`](https://github.com/fasten-project/fasten-docker-deployment/blob/501d944c0f0895d50dcf3b0210831e5791b2320b/docker-compose.yml#L595) container.
> So the question is:
> If I [feed](https://github.com/fasten-project/fasten-docker-deployment#feeding-the-pipeline) the database with package information, this information is send to the [`kafka`](https://github.com/fasten-project/fasten-docker-deployment/blob/501d944c0f0895d50dcf3b0210831e5791b2320b/docker-compose.yml#L37) container. What happens with that information, does the `pycg` container use that information to create a Call Graph for those packages and why, how, and where does the Call Graph format changes?
> 
> Maybe @MagielBruntink knows?

Some further comments. The proper endpoint to download a callgraph would be `/rcg` not `/callgraph` but it won't work currently because the REST API will not properly handle the PyPi package name. The REST API is built for Maven, and while some of it works also for Python, not everything...

Fixes would be needed eg. here:
https://github.com/fasten-project/fasten/blob/142891de4147f9bb50503b3a3b08727d9be96cfa/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/PackageApiServiceImpl.java#L124

**Comment by amphioxis** [comment]
Closed because the `\rcg` endpoint for python if working. Thx!
