### ISSUE TITLE
Feed database with metadata information

### ISSUE THREAD

**Issue by amphioxis** [fasten-project/fasten-pypi-plugin#9]
Hey @mir-am ,
I was trying to feed the docker-compose [python pipeline](https://github.com/fasten-project/fasten-docker-deployment) with metadata information like you suggested but its not working.

What I did:

1. Run the python and vulnerabilities pipeline:
```
sudo docker-compose up --profile python up -d
sudo docker-compose up --profile vulnerabilites up -d
```

2. Feed the pipeline with the [testPackages.txt](https://github.com/fasten-project/fasten-pypi-plugin/blob/development/testPackages.txt)-file:
```
cat testPackages.txt | sudo docker-compose exec -T kafka kafka-console-producer.sh --broker-list kafka:9092 --topic fasten.PyPI.releases --property 'parse.key=true' --property 'key.separator=|'
```
First problem occurring here is that the [fasten-vulnerability-producer](https://github.com/fasten-project/fasten-docker-deployment/blob/92314407a7f9c78df70898d873a07d09f46e2f97/docker-compose.yml#L248) container is stuck in a restarting state (don't know whats causing that).

Second:
I tried to access kafka drop on monster via port forwarding like suggested and that is working.
I can also access the `f4sten.vulnerability.new.out` topic and I see the messages there.

But I am not sure how to proceed from here:

Is it necessary to find a message which matches the packages inside the database? (the packages inside my local database are [those](https://github.com/fasten-project/fasten-pypi-plugin/blob/development/testPackages.txt))
Or can I just use a random message ([vulnerabilities.pypi.txt](https://github.com/fasten-project/fasten-pypi-plugin/blob/development/vulnerabilities.pypi.txt) copied from monster kafka drop and added a package name and version as key there, because without, kafka is complaining about its missing - maybe that's wrong already) and shoot that like
```
cat vulnerabilities.pypi.txt | docker-compose exec -T kafka kafka-console-producer.sh --broker-list kafka:9092 --topic fasten.Vulnerabilities.out --property 'parse.key=true' --property 'key.separator=|'
```
(in the docker-compose pipeline the topic is still [`fasten.Vulnerabilities.out`](https://github.com/fasten-project/fasten-docker-deployment/blob/92314407a7f9c78df70898d873a07d09f46e2f97/docker-compose.yml#L259) as far as I can tell)

Otherwise, how can I get a package from which I know that there is also metadata information accessible.
And how can I find that specific package inside the `f4sten.vulnerability.new.out` topic as there are thousands of messages.

BTW: I am not familiar with kafka, so if you think that those questions are pretty basic I would be happy if you could recommend me some docs where I can find the information I need here.

I am also open for a call if that would speed up the process.

Thx for your help!
```

**Comment by mir-am** [comment]
On your first question, I do know why the vulnerability producer gets stuck in the DC. Normally, it should run as expected. Maybe, @magiel can help here.

Regarding moving vulnerability data from a Kafka topic, use `kafkacat` tool on monster instead of Kafdrop. For instance, the following command gives you one vulnerability record:
```
kafkacat -b delft:9092/kafka -C -t f4sten.vulnerability.new.out -o beginning -e -q -c 1
```
Remove `-c 1` to get all the records or change `1` to an arbitrary number.

Also, note that to feed a Kafka topic you need to specify a key for each record, i.e., `key|record`. Key can be anything, for example, a number from 1...n.

**Comment by amphioxis** [comment]
@mir-am 

Ok, so what you are saying is basically:

Just pick some random vulnerability data from the kafka topic and feed that to the database?
So there is no need that this vulnerability data is related to a specific package?
I can just put any vulnerability data to any package (even though that won't be realistic, but it will be ok for development purposes)

What will be the expected behavior of this?
Right now, with my setup, I can feed the database with package information and access that information for example via curl:
```
curl -X GET localhost:9080/api/pypi/packages
curl -X GET localhost:9080/api/pypi/packages/astroid/
curl -X GET localhost:9080/api/pypi/packages/astroid/2.5.7/
```

What I want is, that if I use for example
```
curl -X GET localhost:9080/api/pypi/packages/astroid/2.5.7/metadata
```
something shows up.

Or more generally asked:

If I feed the vulnerability information into my database, and everything works as expected, how can I access that data?
Like:
```
curl -X GET localhost:9080/api/pypi/packages/{what do I have to put here?}/{and here}/metadata
```

**Comment by amphioxis** [comment]
Hey @gdrosos ,
thx for your intervention!

The problem is, if I pick some random vulnerability message, like [this](https://github.com/fasten-project/fasten-pypi-plugin/blob/development/vulnerabilities.pypi.txt) one (just added a key, in this case `astroid:2.5.7`), where will that be saved?
Or how can I determine where it will be saved?

I know that some endpoints are currently not working, but from our last call I understood that the metadata endpoint is working, it is just lacking information. So right now I am struggling with getting information into that endpoint.

**Comment by gdrosos** [comment]
Yes, indeed the metadata endpoint is working correctly. Regarding the vulnerability information, as far as I understand the [ FASTEN Vulnerability Updates Listener ](https://github.com/fasten-project/fasten/tree/develop/analyzer/vulnerability-statements-processor) listens to messages from the [Vulnerability Producer](https://github.com/fasten-project/vulnerability-producer) and updates the [Metadata Database](https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema) accordingly. But this plugin operates as part of a pipeline, I do not know if it supports a manual population of vulnerability information if I understand correct. Maybe @MagielBruntink can verify.

**Comment by amphioxis** [comment]
Hey guys.
the hint with the access token worked as I really missed that point.

So the current state is:

The `docker-compose` pipeline for python still doesn't work as the [`python-restapi-container`](https://github.com/fasten-project/fasten-docker-deployment/blob/92314407a7f9c78df70898d873a07d09f46e2f97/docker-compose.yml#L943) is stuck in a restarting mode as well throwing
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'knowledgeBaseConnector': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'db.java.url' in value "${db.java.url}"
```

However, if this container is fixed (or it turns out that I am doing something wrong here), I still would need to know how I can feed the metadata information into the database, and especially how I can determine under which package name that metadata information is stored.

To proceed it would be pretty good to have a functioning pipeline in which I can feed at least two different packages, with package name, package version and vulnerability information related to each package.

Thx for the help!

**Comment by amphioxis** [comment]
Closed because all the information I need is accessible via the fasten server directly. So no need to feed specific packages in the docker-compose pipeline anymore for my part.
Also, the docker-compose pipeline is filling itself with vulnerability information, but I guess because the database is missing specific packages, this information can't be accessed.

For example:
Vulnerability information for the packages stored in [testPackages.txt](https://github.com/fasten-project/fasten-pypi-plugin/blob/development/testPackages.txt)  can't be accessed. And those are currently the only packages in my database. However, vulnerability information is stored for a lot of packages.

Thx for your help and hints!
